<?php

return [
    'card_outline_color' => 'card-outline card-warning',
    //btn
    'btn_search' => 'btn-warning',
    'btn_create' => 'btn-warning',
    'btn_login' => 'btn-info',
    'btn_edit' => 'btn-warning',
    'btn_update' => 'btn-warning',
    'btn_save' => 'btn-warning',
    'btn_reset' => 'btn-warning',
    'btn_reload' => 'btn-warning',
    'btn_generate' => 'btn-warning',
    'btn_load' => 'btn-warning',
    'btn_add' => 'btn-outline-warning',
    'btn_changepw' => 'btn-danger',
    'btn_check' => 'btn-outline-secondary',
    'btn_new' => 'btn-outline-danger',
    'tbl_hover' => 'border-left: 3px solid orange;',
    'tbl_tr' => 'border-left: 3px solid #f8f9fa;',
    'link' => 'text-warning',
    'link-disabled' => 'text-muted',
    'breadcrumb' => ' my-0 pt-1 pb-3 h5 font-weight-bold ',
    'card_card_outline_color' => 'card-outline card-gray',
    'card_table_outline_color' => 'card-outline card-light',
    'bg_table' => 'bg-light',
    //'total_underline' => 'border-bottom: 3px double;',
    'grandtotal_underline' => 'border-bottom: 3px double;',
    'card_hd_light' => 'text-muted',
    'tbl_hd_light' => '',
    'total_light' => '',
    'actionline' => 'min-height:38px;',
    'login_card_outline_color' => 'card-outline card-info bg-light',
    'table-info' => 'text-muted',
    'tbl-bottom' => 'border-bottom:solid #dee2e6;',
];